image: dcr.danawa.io/alpine-k8s
stages:
- install
- build
- deploy
before_script:
- mkdir ~/.ssh -p
- cp ${id_rsa} ~/.ssh/id_rsa
- cp ${id_rsa_pub} ~/.ssh/id_rsa.pub
- echo "Host *" > ~/.ssh/config
- echo "StrictHostKeyChecking no" > ~/.ssh/config
- chmod 600 ~/.ssh -R
build:
  stage: build
  when: manual
  script:
  - yum install git -y
  - git clone git@gitlab.danawa.com:ysban/ojt-ide.git
  - cd ojt-ide
  - git branch -v
  - rm -rf package-lock.json
  - npm cache clean -f
  - npm install
  - export VERSION="$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed -E 's/(version)|[:,\",]//g' | tr -d '[[:space:]]')"
  - docker build -t ${REGISTRY}/${FRONT_IMAGE}:latest .
  - docker tag ${REGISTRY}/${FRONT_IMAGE}:latest ${REGISTRY}/${FRONT_IMAGE}:${VERSION}
  - docker push ${REGISTRY}/${FRONT_IMAGE}:latest
  - docker push ${REGISTRY}/${FRONT_IMAGE}:${VERSION}
  - cd ./server
  - docker build -t ${REGISTRY}/${BACKEND_IMAGE}:latest .
  - docker tag ${REGISTRY}/${BACKEND_IMAGE}:latest ${REGISTRY}/${BACKEND_IMAGE}:${VERSION}
  - docker push ${REGISTRY}/${BACKEND_IMAGE}:latest
  - docker push ${REGISTRY}/${BACKEND_IMAGE}:${VERSION}
  - cd ..
  - cd ./mysql
  - docker build -t ${REGISTRY}/${MYSQL_IMAGE}:latest .
  - docker tag ${REGISTRY}/${MYSQL_IMAGE}:latest ${REGISTRY}/${MYSQL_IMAGE}:${VERSION}
  - docker push ${REGISTRY}/${MYSQL_IMAGE}:latest
  - docker push ${REGISTRY}/${MYSQL_IMAGE}:${VERSION}
  - cd ..
  - cd dockerfiles/java-spring
  - docker build -t dcr.danawa.io/java_spring_vscode:latest .
  - cd ..
  - cd node
  - docker build -t dcr.danawa.io/nodejs_vscode:latest .
  
deploy:
  stage: deploy
  when: manual
  script:
  - echo curl -H "x-auth-token=${ESAPI1_TOKEN}" -XPUT ${ESAPI1_URL}
  - curl -H "x-auth-token=${ESAPI1_TOKEN}" -XPUT ${ESAPI1_URL}
  - echo curl -H "x-auth-token=${ESAPI1_BACKEND_TOKEN}" -XPUT ${ESAPI1_BACKEND_URL}
  - curl -H "x-auth-token=${ESAPI1_BACKEND_TOKEN}" -XPUT ${ESAPI1_BACKEND_URL}
  - echo curl -H "x-auth-token=${ESAPI1_MYSQL_TOKEN}" -XPUT ${ESAPI1_MYSQL_URL}
  - curl -H "x-auth-token=${ESAPI1_MYSQL_TOKEN}" -XPUT ${ESAPI1_MYSQL_URL}
  - echo curl -H "x-auth-token=${IMAGE_TOKEN}" -XPUT ${IMAGE_URL}
  - curl -H "x-auth-token=${IMAGE_TOKEN}" -XPUT ${IMAGE_URL}