version: "2"
services: 
  frontend:
    image: dcr-ui.danawa.io/ojt_ide_frontend:latest
    container_name: app_frontend
    ports:
        - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    stdin_open: true

  backend:
    image: dcr-ui.danawa.io/ojt_ide_backend:latest
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./server:/app

  mysql:
    image: dcr.danawa.io/ojt_ide_mysql:latest
    restart: unless-stopped
    container_name: app_mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react