version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:alpine
    labels:
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=80
      - traefik.enable=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
    networks:
      - web